export const gists = {
  loadingGists: false,
  items: [
    {
      "url": "https://api.github.com/gists/3389d90dda98975a7a59dc3e11a34ee7",
      "forks_url": "https://api.github.com/gists/3389d90dda98975a7a59dc3e11a34ee7/forks",
      "commits_url": "https://api.github.com/gists/3389d90dda98975a7a59dc3e11a34ee7/commits",
      "id": "3389d90dda98975a7a59dc3e11a34ee7",
      "node_id": "MDQ6R2lzdDMzODlkOTBkZGE5ODk3NWE3YTU5ZGMzZTExYTM0ZWU3",
      "git_pull_url": "https://gist.github.com/3389d90dda98975a7a59dc3e11a34ee7.git",
      "git_push_url": "https://gist.github.com/3389d90dda98975a7a59dc3e11a34ee7.git",
      "html_url": "https://gist.github.com/3389d90dda98975a7a59dc3e11a34ee7",
      "files": {
        "MarkdownComposer.kt": {
          "filename": "MarkdownComposer.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/3389d90dda98975a7a59dc3e11a34ee7/raw/bac90b5fdf7803f836124c7f1f26891740d580ed/MarkdownComposer.kt",
          "size": 11405
        }
      },
      "public": true,
      "created_at": "2020-09-01T09:28:35Z",
      "updated_at": "2020-09-02T09:13:22Z",
      "description": "A simple rendered for Markdown text parsed using CommonMarks",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/3389d90dda98975a7a59dc3e11a34ee7/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/e94459677fffc26e4803733d30df0987",
      "forks_url": "https://api.github.com/gists/e94459677fffc26e4803733d30df0987/forks",
      "commits_url": "https://api.github.com/gists/e94459677fffc26e4803733d30df0987/commits",
      "id": "e94459677fffc26e4803733d30df0987",
      "node_id": "MDQ6R2lzdGU5NDQ1OTY3N2ZmZmMyNmU0ODAzNzMzZDMwZGYwOTg3",
      "git_pull_url": "https://gist.github.com/e94459677fffc26e4803733d30df0987.git",
      "git_push_url": "https://gist.github.com/e94459677fffc26e4803733d30df0987.git",
      "html_url": "https://gist.github.com/e94459677fffc26e4803733d30df0987",
      "files": {
        "TextFieldText.dart": {
          "filename": "TextFieldText.dart",
          "type": "application/vnd.dart",
          "language": "Dart",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/e94459677fffc26e4803733d30df0987/raw/1c1aaf278f299f55a90602d13eccebef0327109c/TextFieldText.dart",
          "size": 1119
        }
      },
      "public": true,
      "created_at": "2020-04-02T08:28:07Z",
      "updated_at": "2020-04-02T08:48:45Z",
      "description": "Testing the TextField decoration",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/e94459677fffc26e4803733d30df0987/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/d95ba1fa789e598a2ec6d40e69512b8d",
      "forks_url": "https://api.github.com/gists/d95ba1fa789e598a2ec6d40e69512b8d/forks",
      "commits_url": "https://api.github.com/gists/d95ba1fa789e598a2ec6d40e69512b8d/commits",
      "id": "d95ba1fa789e598a2ec6d40e69512b8d",
      "node_id": "MDQ6R2lzdGQ5NWJhMWZhNzg5ZTU5OGEyZWM2ZDQwZTY5NTEyYjhk",
      "git_pull_url": "https://gist.github.com/d95ba1fa789e598a2ec6d40e69512b8d.git",
      "git_push_url": "https://gist.github.com/d95ba1fa789e598a2ec6d40e69512b8d.git",
      "html_url": "https://gist.github.com/d95ba1fa789e598a2ec6d40e69512b8d",
      "files": {
        "LoginScreenWithCompose.kt": {
          "filename": "LoginScreenWithCompose.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/d95ba1fa789e598a2ec6d40e69512b8d/raw/6b7c14328b607213a4078831310fd358318a1b2b/LoginScreenWithCompose.kt",
          "size": 3233
        }
      },
      "public": true,
      "created_at": "2019-12-16T17:51:18Z",
      "updated_at": "2020-11-20T07:35:12Z",
      "description": "A simple demo of using Jetpack Compose to build a Login screen",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/d95ba1fa789e598a2ec6d40e69512b8d/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/084e22d928398dd5faf3d2fc196744eb",
      "forks_url": "https://api.github.com/gists/084e22d928398dd5faf3d2fc196744eb/forks",
      "commits_url": "https://api.github.com/gists/084e22d928398dd5faf3d2fc196744eb/commits",
      "id": "084e22d928398dd5faf3d2fc196744eb",
      "node_id": "MDQ6R2lzdDA4NGUyMmQ5MjgzOThkZDVmYWYzZDJmYzE5Njc0NGVi",
      "git_pull_url": "https://gist.github.com/084e22d928398dd5faf3d2fc196744eb.git",
      "git_push_url": "https://gist.github.com/084e22d928398dd5faf3d2fc196744eb.git",
      "html_url": "https://gist.github.com/084e22d928398dd5faf3d2fc196744eb",
      "files": {
        "KittyLog.kt": {
          "filename": "KittyLog.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/084e22d928398dd5faf3d2fc196744eb/raw/2943e080eb04413459865c7f25055c715048ebad/KittyLog.kt",
          "size": 1698
        }
      },
      "public": true,
      "created_at": "2019-08-19T09:28:18Z",
      "updated_at": "2019-09-04T08:46:22Z",
      "description": "A super tiny wrapper for Android Log utility that allows log printing in unit tests. For a more advanced log wrapper for Android, see https://github.com/JakeWharton/timber/",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/084e22d928398dd5faf3d2fc196744eb/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/38da213fef9b3bdb36421eca1ec715cd",
      "forks_url": "https://api.github.com/gists/38da213fef9b3bdb36421eca1ec715cd/forks",
      "commits_url": "https://api.github.com/gists/38da213fef9b3bdb36421eca1ec715cd/commits",
      "id": "38da213fef9b3bdb36421eca1ec715cd",
      "node_id": "MDQ6R2lzdDM4ZGEyMTNmZWY5YjNiZGIzNjQyMWVjYTFlYzcxNWNk",
      "git_pull_url": "https://gist.github.com/38da213fef9b3bdb36421eca1ec715cd.git",
      "git_push_url": "https://gist.github.com/38da213fef9b3bdb36421eca1ec715cd.git",
      "html_url": "https://gist.github.com/38da213fef9b3bdb36421eca1ec715cd",
      "files": {
        "KittyLog.kt": {
          "filename": "KittyLog.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/38da213fef9b3bdb36421eca1ec715cd/raw/862b64bc002823a45a9be431989d408689725120/KittyLog.kt",
          "size": 1575
        }
      },
      "public": true,
      "created_at": "2019-08-19T09:19:13Z",
      "updated_at": "2019-08-19T09:19:13Z",
      "description": "A super tiny wrapper for Android Log utility. ",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/38da213fef9b3bdb36421eca1ec715cd/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/7f2b28a68fd01c6c079725083e8fc202",
      "forks_url": "https://api.github.com/gists/7f2b28a68fd01c6c079725083e8fc202/forks",
      "commits_url": "https://api.github.com/gists/7f2b28a68fd01c6c079725083e8fc202/commits",
      "id": "7f2b28a68fd01c6c079725083e8fc202",
      "node_id": "MDQ6R2lzdDdmMmIyOGE2OGZkMDFjNmMwNzk3MjUwODNlOGZjMjAy",
      "git_pull_url": "https://gist.github.com/7f2b28a68fd01c6c079725083e8fc202.git",
      "git_push_url": "https://gist.github.com/7f2b28a68fd01c6c079725083e8fc202.git",
      "html_url": "https://gist.github.com/7f2b28a68fd01c6c079725083e8fc202",
      "files": {
        "NonBlockingEchoServer.kt": {
          "filename": "NonBlockingEchoServer.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/7f2b28a68fd01c6c079725083e8fc202/raw/a1d99ecb460edb9bcd392268a85451617cb6bf09/NonBlockingEchoServer.kt",
          "size": 3517
        }
      },
      "public": true,
      "created_at": "2019-08-16T13:01:22Z",
      "updated_at": "2020-09-07T06:01:09Z",
      "description": "A very simple example of an echo-server using the non-blocking Java I/O APIs",
      "comments": 1,
      "user": null,
      "comments_url": "https://api.github.com/gists/7f2b28a68fd01c6c079725083e8fc202/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/7767188ef6ddbab1a6d134888e5fc4f0",
      "forks_url": "https://api.github.com/gists/7767188ef6ddbab1a6d134888e5fc4f0/forks",
      "commits_url": "https://api.github.com/gists/7767188ef6ddbab1a6d134888e5fc4f0/commits",
      "id": "7767188ef6ddbab1a6d134888e5fc4f0",
      "node_id": "MDQ6R2lzdDc3NjcxODhlZjZkZGJhYjFhNmQxMzQ4ODhlNWZjNGYw",
      "git_pull_url": "https://gist.github.com/7767188ef6ddbab1a6d134888e5fc4f0.git",
      "git_push_url": "https://gist.github.com/7767188ef6ddbab1a6d134888e5fc4f0.git",
      "html_url": "https://gist.github.com/7767188ef6ddbab1a6d134888e5fc4f0",
      "files": {
        "ImageFormatName.kt": {
          "filename": "ImageFormatName.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/7767188ef6ddbab1a6d134888e5fc4f0/raw/a3af5da5b3254518fc3d74cb8fdb2c555bf620e3/ImageFormatName.kt",
          "size": 930
        },
        "PixelFormatName.kt": {
          "filename": "PixelFormatName.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/7767188ef6ddbab1a6d134888e5fc4f0/raw/0fb476d6120d4149165e4d7c4de80348dd21893a/PixelFormatName.kt",
          "size": 891
        }
      },
      "public": true,
      "created_at": "2019-08-08T06:34:43Z",
      "updated_at": "2019-08-08T08:01:19Z",
      "description": "Kotlin functions for getting the name of an ImageFormat or PixelFormat Integer.",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/7767188ef6ddbab1a6d134888e5fc4f0/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/3d131596a8d6a10eb78c418a64281cf5",
      "forks_url": "https://api.github.com/gists/3d131596a8d6a10eb78c418a64281cf5/forks",
      "commits_url": "https://api.github.com/gists/3d131596a8d6a10eb78c418a64281cf5/commits",
      "id": "3d131596a8d6a10eb78c418a64281cf5",
      "node_id": "MDQ6R2lzdDNkMTMxNTk2YThkNmExMGViNzhjNDE4YTY0MjgxY2Y1",
      "git_pull_url": "https://gist.github.com/3d131596a8d6a10eb78c418a64281cf5.git",
      "git_push_url": "https://gist.github.com/3d131596a8d6a10eb78c418a64281cf5.git",
      "html_url": "https://gist.github.com/3d131596a8d6a10eb78c418a64281cf5",
      "files": {
        "WebViewServer.kt": {
          "filename": "WebViewServer.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/3d131596a8d6a10eb78c418a64281cf5/raw/0fa14aaac7ce95611b721c1642249e554ccf5d90/WebViewServer.kt",
          "size": 5791
        }
      },
      "public": true,
      "created_at": "2019-04-08T07:23:12Z",
      "updated_at": "2020-10-02T02:35:54Z",
      "description": "This class is no longer needed now that Google provides WebViewAssetLoader (see https://developer.android.com/reference/kotlin/androidx/webkit/WebViewAssetLoader)",
      "comments": 4,
      "user": null,
      "comments_url": "https://api.github.com/gists/3d131596a8d6a10eb78c418a64281cf5/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/b158b41cb4bfb2b53345c686bd6950df",
      "forks_url": "https://api.github.com/gists/b158b41cb4bfb2b53345c686bd6950df/forks",
      "commits_url": "https://api.github.com/gists/b158b41cb4bfb2b53345c686bd6950df/commits",
      "id": "b158b41cb4bfb2b53345c686bd6950df",
      "node_id": "MDQ6R2lzdGIxNThiNDFjYjRiZmIyYjUzMzQ1YzY4NmJkNjk1MGRm",
      "git_pull_url": "https://gist.github.com/b158b41cb4bfb2b53345c686bd6950df.git",
      "git_push_url": "https://gist.github.com/b158b41cb4bfb2b53345c686bd6950df.git",
      "html_url": "https://gist.github.com/b158b41cb4bfb2b53345c686bd6950df",
      "files": {
        "WebViewServer.kt": {
          "filename": "WebViewServer.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/b158b41cb4bfb2b53345c686bd6950df/raw/94f0883a9dd1754a42021bb4f2cc8f22c49480fc/WebViewServer.kt",
          "size": 4715
        }
      },
      "public": true,
      "created_at": "2019-04-08T07:23:10Z",
      "updated_at": "2019-04-08T07:23:10Z",
      "description": "A simple \"web server\" for handling intercepted WebView requests on Android and deliver local content.",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/b158b41cb4bfb2b53345c686bd6950df/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/b325036d47b0b49486be9c3e31296351",
      "forks_url": "https://api.github.com/gists/b325036d47b0b49486be9c3e31296351/forks",
      "commits_url": "https://api.github.com/gists/b325036d47b0b49486be9c3e31296351/commits",
      "id": "b325036d47b0b49486be9c3e31296351",
      "node_id": "MDQ6R2lzdGIzMjUwMzZkNDdiMGI0OTQ4NmJlOWMzZTMxMjk2MzUx",
      "git_pull_url": "https://gist.github.com/b325036d47b0b49486be9c3e31296351.git",
      "git_push_url": "https://gist.github.com/b325036d47b0b49486be9c3e31296351.git",
      "html_url": "https://gist.github.com/b325036d47b0b49486be9c3e31296351",
      "files": {
        "generateSelector.js": {
          "filename": "generateSelector.js",
          "type": "application/javascript",
          "language": "JavaScript",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/b325036d47b0b49486be9c3e31296351/raw/876ff10ca3172c83ad60baecac64f6ba7ee1bdd0/generateSelector.js",
          "size": 1013
        }
      },
      "public": true,
      "created_at": "2019-01-09T16:48:26Z",
      "updated_at": "2019-01-10T06:57:10Z",
      "description": "Generate a selector for an element.",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/b325036d47b0b49486be9c3e31296351/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/9e17f2ea6a78669294ef2af4bc3f5878",
      "forks_url": "https://api.github.com/gists/9e17f2ea6a78669294ef2af4bc3f5878/forks",
      "commits_url": "https://api.github.com/gists/9e17f2ea6a78669294ef2af4bc3f5878/commits",
      "id": "9e17f2ea6a78669294ef2af4bc3f5878",
      "node_id": "MDQ6R2lzdDllMTdmMmVhNmE3ODY2OTI5NGVmMmFmNGJjM2Y1ODc4",
      "git_pull_url": "https://gist.github.com/9e17f2ea6a78669294ef2af4bc3f5878.git",
      "git_push_url": "https://gist.github.com/9e17f2ea6a78669294ef2af4bc3f5878.git",
      "html_url": "https://gist.github.com/9e17f2ea6a78669294ef2af4bc3f5878",
      "files": {
        "LitElementDialogExample.js": {
          "filename": "LitElementDialogExample.js",
          "type": "application/javascript",
          "language": "JavaScript",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/9e17f2ea6a78669294ef2af4bc3f5878/raw/cc77ec44ceff571f74ae8844ce8f326f6a2932e9/LitElementDialogExample.js",
          "size": 1999
        }
      },
      "public": true,
      "created_at": "2018-10-12T08:46:44Z",
      "updated_at": "2021-01-24T11:35:46Z",
      "description": "Basic dialog example with LitElement",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/9e17f2ea6a78669294ef2af4bc3f5878/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/1d99c38a5b0103e930de166bcc019942",
      "forks_url": "https://api.github.com/gists/1d99c38a5b0103e930de166bcc019942/forks",
      "commits_url": "https://api.github.com/gists/1d99c38a5b0103e930de166bcc019942/commits",
      "id": "1d99c38a5b0103e930de166bcc019942",
      "node_id": "MDQ6R2lzdDFkOTljMzhhNWIwMTAzZTkzMGRlMTY2YmNjMDE5OTQy",
      "git_pull_url": "https://gist.github.com/1d99c38a5b0103e930de166bcc019942.git",
      "git_push_url": "https://gist.github.com/1d99c38a5b0103e930de166bcc019942.git",
      "html_url": "https://gist.github.com/1d99c38a5b0103e930de166bcc019942",
      "files": {
        "SimpleService.kt": {
          "filename": "SimpleService.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/1d99c38a5b0103e930de166bcc019942/raw/208a75ac09ce2f5dd42cbd60deecb588e9ec8e1b/SimpleService.kt",
          "size": 505
        }
      },
      "public": true,
      "created_at": "2018-01-16T07:09:52Z",
      "updated_at": "2018-01-16T07:09:52Z",
      "description": "",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/1d99c38a5b0103e930de166bcc019942/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/f80c2a578455b103aa7086054f80fbff",
      "forks_url": "https://api.github.com/gists/f80c2a578455b103aa7086054f80fbff/forks",
      "commits_url": "https://api.github.com/gists/f80c2a578455b103aa7086054f80fbff/commits",
      "id": "f80c2a578455b103aa7086054f80fbff",
      "node_id": "MDQ6R2lzdGY4MGMyYTU3ODQ1NWIxMDNhYTcwODYwNTRmODBmYmZm",
      "git_pull_url": "https://gist.github.com/f80c2a578455b103aa7086054f80fbff.git",
      "git_push_url": "https://gist.github.com/f80c2a578455b103aa7086054f80fbff.git",
      "html_url": "https://gist.github.com/f80c2a578455b103aa7086054f80fbff",
      "files": {
        "BackgroundThreadFunction.kt": {
          "filename": "BackgroundThreadFunction.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/f80c2a578455b103aa7086054f80fbff/raw/effad9f8c60c88c410ecbf0550953bf37b39422d/BackgroundThreadFunction.kt",
          "size": 64
        }
      },
      "public": true,
      "created_at": "2018-01-16T07:02:17Z",
      "updated_at": "2018-01-16T07:09:40Z",
      "description": "Background Thread Function",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/f80c2a578455b103aa7086054f80fbff/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/057ce5de3d438233532d6787cb00b0ea",
      "forks_url": "https://api.github.com/gists/057ce5de3d438233532d6787cb00b0ea/forks",
      "commits_url": "https://api.github.com/gists/057ce5de3d438233532d6787cb00b0ea/commits",
      "id": "057ce5de3d438233532d6787cb00b0ea",
      "node_id": "MDQ6R2lzdDA1N2NlNWRlM2Q0MzgyMzM1MzJkNjc4N2NiMDBiMGVh",
      "git_pull_url": "https://gist.github.com/057ce5de3d438233532d6787cb00b0ea.git",
      "git_push_url": "https://gist.github.com/057ce5de3d438233532d6787cb00b0ea.git",
      "html_url": "https://gist.github.com/057ce5de3d438233532d6787cb00b0ea",
      "files": {
        "kotlin_coroutine_android_loader.kt": {
          "filename": "kotlin_coroutine_android_loader.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/057ce5de3d438233532d6787cb00b0ea/raw/b20dc5cd8874f8a2870b3ec8844d7a88c47832dc/kotlin_coroutine_android_loader.kt",
          "size": 902
        }
      },
      "public": true,
      "created_at": "2017-12-23T19:54:18Z",
      "updated_at": "2020-03-20T20:42:18Z",
      "description": "Kotlin Coroutine Android Loader",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/057ce5de3d438233532d6787cb00b0ea/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/8efdb102fd361b3cba1eef8bdebf8dcf",
      "forks_url": "https://api.github.com/gists/8efdb102fd361b3cba1eef8bdebf8dcf/forks",
      "commits_url": "https://api.github.com/gists/8efdb102fd361b3cba1eef8bdebf8dcf/commits",
      "id": "8efdb102fd361b3cba1eef8bdebf8dcf",
      "node_id": "MDQ6R2lzdDhlZmRiMTAyZmQzNjFiM2NiYTFlZWY4YmRlYmY4ZGNm",
      "git_pull_url": "https://gist.github.com/8efdb102fd361b3cba1eef8bdebf8dcf.git",
      "git_push_url": "https://gist.github.com/8efdb102fd361b3cba1eef8bdebf8dcf.git",
      "html_url": "https://gist.github.com/8efdb102fd361b3cba1eef8bdebf8dcf",
      "files": {
        "twig.kt": {
          "filename": "twig.kt",
          "type": "text/plain",
          "language": "Kotlin",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/8efdb102fd361b3cba1eef8bdebf8dcf/raw/e3e196c2e62a868d1886076bb885bc9466912120/twig.kt",
          "size": 2598
        }
      },
      "public": true,
      "created_at": "2017-11-07T12:43:50Z",
      "updated_at": "2017-11-21T09:31:12Z",
      "description": "Twig - A logcat wrapper using Kotlin reified generics",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/8efdb102fd361b3cba1eef8bdebf8dcf/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/c76bff4bc8daf8cb9931d98bf892e151",
      "forks_url": "https://api.github.com/gists/c76bff4bc8daf8cb9931d98bf892e151/forks",
      "commits_url": "https://api.github.com/gists/c76bff4bc8daf8cb9931d98bf892e151/commits",
      "id": "c76bff4bc8daf8cb9931d98bf892e151",
      "node_id": "MDQ6R2lzdGM3NmJmZjRiYzhkYWY4Y2I5OTMxZDk4YmY4OTJlMTUx",
      "git_pull_url": "https://gist.github.com/c76bff4bc8daf8cb9931d98bf892e151.git",
      "git_push_url": "https://gist.github.com/c76bff4bc8daf8cb9931d98bf892e151.git",
      "html_url": "https://gist.github.com/c76bff4bc8daf8cb9931d98bf892e151",
      "files": {
        "RxJavaAndDiffUtil.java": {
          "filename": "RxJavaAndDiffUtil.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/c76bff4bc8daf8cb9931d98bf892e151/raw/d0d2860952cb2cfe1bb26a49ac3a83fa7b061cef/RxJavaAndDiffUtil.java",
          "size": 1013
        }
      },
      "public": true,
      "created_at": "2017-04-02T13:41:57Z",
      "updated_at": "2018-06-05T13:58:27Z",
      "description": "RxJava & DiffUtil",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/c76bff4bc8daf8cb9931d98bf892e151/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/fec71cc0635897a15d97f8bb050475e5",
      "forks_url": "https://api.github.com/gists/fec71cc0635897a15d97f8bb050475e5/forks",
      "commits_url": "https://api.github.com/gists/fec71cc0635897a15d97f8bb050475e5/commits",
      "id": "fec71cc0635897a15d97f8bb050475e5",
      "node_id": "MDQ6R2lzdGZlYzcxY2MwNjM1ODk3YTE1ZDk3ZjhiYjA1MDQ3NWU1",
      "git_pull_url": "https://gist.github.com/fec71cc0635897a15d97f8bb050475e5.git",
      "git_push_url": "https://gist.github.com/fec71cc0635897a15d97f8bb050475e5.git",
      "html_url": "https://gist.github.com/fec71cc0635897a15d97f8bb050475e5",
      "files": {
        "gistfile1.txt": {
          "filename": "gistfile1.txt",
          "type": "text/plain",
          "language": "Text",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/fec71cc0635897a15d97f8bb050475e5/raw/47a45901dc076ef9cffde8c0c3e9af9c584b2c07/gistfile1.txt",
          "size": 84
        }
      },
      "public": true,
      "created_at": "2017-01-19T12:03:06Z",
      "updated_at": "2017-01-19T12:03:06Z",
      "description": "",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/fec71cc0635897a15d97f8bb050475e5/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/061ac7ea4f8fc34a45091b889072d9a9",
      "forks_url": "https://api.github.com/gists/061ac7ea4f8fc34a45091b889072d9a9/forks",
      "commits_url": "https://api.github.com/gists/061ac7ea4f8fc34a45091b889072d9a9/commits",
      "id": "061ac7ea4f8fc34a45091b889072d9a9",
      "node_id": "MDQ6R2lzdDA2MWFjN2VhNGY4ZmMzNGE0NTA5MWI4ODkwNzJkOWE5",
      "git_pull_url": "https://gist.github.com/061ac7ea4f8fc34a45091b889072d9a9.git",
      "git_push_url": "https://gist.github.com/061ac7ea4f8fc34a45091b889072d9a9.git",
      "html_url": "https://gist.github.com/061ac7ea4f8fc34a45091b889072d9a9",
      "files": {
        "MainActivity.java": {
          "filename": "MainActivity.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/061ac7ea4f8fc34a45091b889072d9a9/raw/153e4ddfc559eac691f0d84125c506c2912c5d9c/MainActivity.java",
          "size": 3375
        },
        "MyService.java": {
          "filename": "MyService.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/061ac7ea4f8fc34a45091b889072d9a9/raw/c965b8c720fdd1d1384a074782663e377a28c44e/MyService.java",
          "size": 7451
        }
      },
      "public": true,
      "created_at": "2016-04-01T10:07:59Z",
      "updated_at": "2018-07-13T08:57:47Z",
      "description": "Async communication with Service",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/061ac7ea4f8fc34a45091b889072d9a9/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/148434264edb186d5498",
      "forks_url": "https://api.github.com/gists/148434264edb186d5498/forks",
      "commits_url": "https://api.github.com/gists/148434264edb186d5498/commits",
      "id": "148434264edb186d5498",
      "node_id": "MDQ6R2lzdDE0ODQzNDI2NGVkYjE4NmQ1NDk4",
      "git_pull_url": "https://gist.github.com/148434264edb186d5498.git",
      "git_push_url": "https://gist.github.com/148434264edb186d5498.git",
      "html_url": "https://gist.github.com/148434264edb186d5498",
      "files": {
        "MainActivity.java": {
          "filename": "MainActivity.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/148434264edb186d5498/raw/80652360548e665a0c1c037b0f32a3053f36bc6b/MainActivity.java",
          "size": 2881
        }
      },
      "public": true,
      "created_at": "2016-03-23T13:46:36Z",
      "updated_at": "2016-03-23T13:46:36Z",
      "description": "Demo of using Handlers for async operations in Android",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/148434264edb186d5498/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/bf3c94090888994b3c5e",
      "forks_url": "https://api.github.com/gists/bf3c94090888994b3c5e/forks",
      "commits_url": "https://api.github.com/gists/bf3c94090888994b3c5e/commits",
      "id": "bf3c94090888994b3c5e",
      "node_id": "MDQ6R2lzdGJmM2M5NDA5MDg4ODk5NGIzYzVl",
      "git_pull_url": "https://gist.github.com/bf3c94090888994b3c5e.git",
      "git_push_url": "https://gist.github.com/bf3c94090888994b3c5e.git",
      "html_url": "https://gist.github.com/bf3c94090888994b3c5e",
      "files": {
        "RxGattWrapper.java": {
          "filename": "RxGattWrapper.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/bf3c94090888994b3c5e/raw/50f753df4746b52cdf05f96e7fb44ca3c882bbc6/RxGattWrapper.java",
          "size": 6029
        }
      },
      "public": true,
      "created_at": "2015-09-24T08:22:57Z",
      "updated_at": "2015-09-24T08:22:57Z",
      "description": "A base for a wrapper for the Bluetooth LE API on Android",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/bf3c94090888994b3c5e/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/0678bfde870a82f182e4",
      "forks_url": "https://api.github.com/gists/0678bfde870a82f182e4/forks",
      "commits_url": "https://api.github.com/gists/0678bfde870a82f182e4/commits",
      "id": "0678bfde870a82f182e4",
      "node_id": "MDQ6R2lzdDA2NzhiZmRlODcwYTgyZjE4MmU0",
      "git_pull_url": "https://gist.github.com/0678bfde870a82f182e4.git",
      "git_push_url": "https://gist.github.com/0678bfde870a82f182e4.git",
      "html_url": "https://gist.github.com/0678bfde870a82f182e4",
      "files": {
        "gradle_tips_for_android.md": {
          "filename": "gradle_tips_for_android.md",
          "type": "text/markdown",
          "language": "Markdown",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/0678bfde870a82f182e4/raw/8e14f6ebebbbb968bdfc0cfca3f077139963f030/gradle_tips_for_android.md",
          "size": 3493
        }
      },
      "public": true,
      "created_at": "2015-05-09T09:30:27Z",
      "updated_at": "2015-08-29T14:20:51Z",
      "description": "Boosting the performance for Gradle in your Android projects",
      "comments": 1,
      "user": null,
      "comments_url": "https://api.github.com/gists/0678bfde870a82f182e4/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/c57540f85056fa15a13d",
      "forks_url": "https://api.github.com/gists/c57540f85056fa15a13d/forks",
      "commits_url": "https://api.github.com/gists/c57540f85056fa15a13d/commits",
      "id": "c57540f85056fa15a13d",
      "node_id": "MDQ6R2lzdGM1NzU0MGY4NTA1NmZhMTVhMTNk",
      "git_pull_url": "https://gist.github.com/c57540f85056fa15a13d.git",
      "git_push_url": "https://gist.github.com/c57540f85056fa15a13d.git",
      "html_url": "https://gist.github.com/c57540f85056fa15a13d",
      "files": {
        "keybase.md": {
          "filename": "keybase.md",
          "type": "text/markdown",
          "language": "Markdown",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/c57540f85056fa15a13d/raw/a783cf9158167ef22ca20b0bc3514d532986851b/keybase.md",
          "size": 2663
        }
      },
      "public": true,
      "created_at": "2015-04-03T17:50:55Z",
      "updated_at": "2015-08-29T14:18:23Z",
      "description": "keybase.md",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/c57540f85056fa15a13d/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/4b6ecc87d1b37c9809d1",
      "forks_url": "https://api.github.com/gists/4b6ecc87d1b37c9809d1/forks",
      "commits_url": "https://api.github.com/gists/4b6ecc87d1b37c9809d1/commits",
      "id": "4b6ecc87d1b37c9809d1",
      "node_id": "MDQ6R2lzdDRiNmVjYzg3ZDFiMzdjOTgwOWQx",
      "git_pull_url": "https://gist.github.com/4b6ecc87d1b37c9809d1.git",
      "git_push_url": "https://gist.github.com/4b6ecc87d1b37c9809d1.git",
      "html_url": "https://gist.github.com/4b6ecc87d1b37c9809d1",
      "files": {
        "MyActivity.java": {
          "filename": "MyActivity.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/4b6ecc87d1b37c9809d1/raw/27e12e48235c7ad2fdff838482a27518517fff3d/MyActivity.java",
          "size": 1802
        },
        "MyService.java": {
          "filename": "MyService.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/4b6ecc87d1b37c9809d1/raw/a5bfa491a6162c80221306746454f50c5a4a1879/MyService.java",
          "size": 867
        }
      },
      "public": true,
      "created_at": "2014-10-13T15:54:37Z",
      "updated_at": "2019-08-12T10:23:10Z",
      "description": "Simple LocalBinder demo for Android",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/4b6ecc87d1b37c9809d1/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/d4c04005ec4401e3213a",
      "forks_url": "https://api.github.com/gists/d4c04005ec4401e3213a/forks",
      "commits_url": "https://api.github.com/gists/d4c04005ec4401e3213a/commits",
      "id": "d4c04005ec4401e3213a",
      "node_id": "MDQ6R2lzdGQ0YzA0MDA1ZWM0NDAxZTMyMTNh",
      "git_pull_url": "https://gist.github.com/d4c04005ec4401e3213a.git",
      "git_push_url": "https://gist.github.com/d4c04005ec4401e3213a.git",
      "html_url": "https://gist.github.com/d4c04005ec4401e3213a",
      "files": {
        "VisualizationRenderer": {
          "filename": "VisualizationRenderer",
          "type": "text/plain",
          "language": null,
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/d4c04005ec4401e3213a/raw/aa59b4273432e715c912a219e46e4ca0b4d28553/VisualizationRenderer",
          "size": 4406
        }
      },
      "public": true,
      "created_at": "2014-08-29T13:26:38Z",
      "updated_at": "2015-08-29T14:05:51Z",
      "description": "Simple renderer for a pixel shader on Android",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/d4c04005ec4401e3213a/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/df18e23066285d0cfbbe",
      "forks_url": "https://api.github.com/gists/df18e23066285d0cfbbe/forks",
      "commits_url": "https://api.github.com/gists/df18e23066285d0cfbbe/commits",
      "id": "df18e23066285d0cfbbe",
      "node_id": "MDQ6R2lzdGRmMThlMjMwNjYyODVkMGNmYmJl",
      "git_pull_url": "https://gist.github.com/df18e23066285d0cfbbe.git",
      "git_push_url": "https://gist.github.com/df18e23066285d0cfbbe.git",
      "html_url": "https://gist.github.com/df18e23066285d0cfbbe",
      "files": {
        "MyActivity.java": {
          "filename": "MyActivity.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/df18e23066285d0cfbbe/raw/b695c1436e1080ad5a3958d0514482495bcd31c2/MyActivity.java",
          "size": 3210
        }
      },
      "public": true,
      "created_at": "2014-07-27T13:25:50Z",
      "updated_at": "2018-06-08T14:02:16Z",
      "description": "Android sample showing how to use Handlers for efficient foreground/background operations.",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/df18e23066285d0cfbbe/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/8704874",
      "forks_url": "https://api.github.com/gists/8704874/forks",
      "commits_url": "https://api.github.com/gists/8704874/commits",
      "id": "8704874",
      "node_id": "MDQ6R2lzdDg3MDQ4NzQ=",
      "git_pull_url": "https://gist.github.com/8704874.git",
      "git_push_url": "https://gist.github.com/8704874.git",
      "html_url": "https://gist.github.com/8704874",
      "files": {
        "personer.json": {
          "filename": "personer.json",
          "type": "application/json",
          "language": "JSON",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/8704874/raw/b65c69c25a1eb7b8356fc5229fe3748872cafb79/personer.json",
          "size": 237
        }
      },
      "public": true,
      "created_at": "2014-01-30T08:56:45Z",
      "updated_at": "2015-08-29T13:55:48Z",
      "description": "",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/8704874/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/6069322",
      "forks_url": "https://api.github.com/gists/6069322/forks",
      "commits_url": "https://api.github.com/gists/6069322/commits",
      "id": "6069322",
      "node_id": "MDQ6R2lzdDYwNjkzMjI=",
      "git_pull_url": "https://gist.github.com/6069322.git",
      "git_push_url": "https://gist.github.com/6069322.git",
      "html_url": "https://gist.github.com/6069322",
      "files": {
        "PaintView.java": {
          "filename": "PaintView.java",
          "type": "text/x-java-source",
          "language": "Java",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/6069322/raw/fab3373dd4c64a5566630c9c0e5833ae2a0f1e6b/PaintView.java",
          "size": 2966
        }
      },
      "public": true,
      "created_at": "2013-07-24T09:56:54Z",
      "updated_at": "2019-10-08T17:33:13Z",
      "description": "A very simple example of using multi-touch on Android to build a custom View for finger painting.\r\n\r\nThis example uses the Path class from the android.graphics package. Feel free to use this code as you wish for your own multi-touch apps.",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/6069322/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/6055718",
      "forks_url": "https://api.github.com/gists/6055718/forks",
      "commits_url": "https://api.github.com/gists/6055718/commits",
      "id": "6055718",
      "node_id": "MDQ6R2lzdDYwNTU3MTg=",
      "git_pull_url": "https://gist.github.com/6055718.git",
      "git_push_url": "https://gist.github.com/6055718.git",
      "html_url": "https://gist.github.com/6055718",
      "files": {
        "gistfile1.txt": {
          "filename": "gistfile1.txt",
          "type": "text/plain",
          "language": "Text",
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/6055718/raw/f796636d9a6de768e5ca80f710dc8ae9a1caa918/gistfile1.txt",
          "size": 1410
        }
      },
      "public": true,
      "created_at": "2013-07-22T17:17:25Z",
      "updated_at": "2015-12-20T02:19:33Z",
      "description": "GLES Shader for edge detection",
      "comments": 0,
      "user": null,
      "comments_url": "https://api.github.com/gists/6055718/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    },
    {
      "url": "https://api.github.com/gists/5840101",
      "forks_url": "https://api.github.com/gists/5840101/forks",
      "commits_url": "https://api.github.com/gists/5840101/commits",
      "id": "5840101",
      "node_id": "MDQ6R2lzdDU4NDAxMDE=",
      "git_pull_url": "https://gist.github.com/5840101.git",
      "git_push_url": "https://gist.github.com/5840101.git",
      "html_url": "https://gist.github.com/5840101",
      "files": {
        "Activity showing surface switch ": {
          "filename": "Activity showing surface switch ",
          "type": "text/plain",
          "language": null,
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/5840101/raw/9ca41bc824fc805d57df55cdd9bbdd4d1189da40/Activity%20showing%20surface%20switch%20",
          "size": 3737
        },
        "XML layout with two SurfaceViews": {
          "filename": "XML layout with two SurfaceViews",
          "type": "text/plain",
          "language": null,
          "raw_url": "https://gist.githubusercontent.com/ErikHellman/5840101/raw/80e0bc71f68f01b26cc7f25619ca1d4ca73a7614/XML%20layout%20with%20two%20SurfaceViews",
          "size": 1426
        }
      },
      "public": true,
      "created_at": "2013-06-22T09:17:18Z",
      "updated_at": "2021-03-14T00:42:07Z",
      "description": "A simple demo of playing a video on one SurfaceView and switching to another during playback.",
      "comments": 1,
      "user": null,
      "comments_url": "https://api.github.com/gists/5840101/comments",
      "owner": {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false
      },
      "truncated": false
    }
  ]
}
  